[package]
name = "hyperliquid-db-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
hyperliquid-db-core.workspace = true
hyperliquid-db-fs.workspace = true
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
